name: Convert TODOs to Issue

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  todo-to-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          IDENTIFIERS: '[{"name": "BUG", "labels": []}, {"name": "FIXME", "labels": []}, {"name": "TODO", "labels": []}]'
          INSERT_ISSUE_URLS: "true"

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add -A
          git stash --include-untracked

          git pull --rebase origin main

          git stash pop || {
            echo "Stash pop failed. Skipping push."
            exit 0
          }

          git add -A
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
